// flow-typed signature: d175b8e814c664ac663eff67ac262362
// flow-typed version: <<STUB>>/babel-plugin-add-module-exports_v0.2.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-add-module-exports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-add-module-exports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-add-module-exports/changelog' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-module-exports/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-add-module-exports/changelog.js' {
  declare module.exports: $Exports<'babel-plugin-add-module-exports/changelog'>;
}
declare module 'babel-plugin-add-module-exports/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-add-module-exports/lib/index'>;
}
