// flow-typed signature: 9ccaba5980110aba47a12040f738f19d
// flow-typed version: <<STUB>>/serialport_v^4.0.7/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serialport/bin/serialport-list' {
  declare module.exports: any;
}

declare module 'serialport/bin/serialport-terminal' {
  declare module.exports: any;
}

declare module 'serialport/lib/bindings' {
  declare module.exports: any;
}

declare module 'serialport/lib/list-unix' {
  declare module.exports: any;
}

declare module 'serialport/lib/parsers' {
  declare module.exports: any;
}

declare module 'serialport/lib/serialport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serialport/bin/serialport-list.js' {
  declare module.exports: $Exports<'serialport/bin/serialport-list'>;
}
declare module 'serialport/bin/serialport-terminal.js' {
  declare module.exports: $Exports<'serialport/bin/serialport-terminal'>;
}
declare module 'serialport/lib/bindings.js' {
  declare module.exports: $Exports<'serialport/lib/bindings'>;
}
declare module 'serialport/lib/list-unix.js' {
  declare module.exports: $Exports<'serialport/lib/list-unix'>;
}
declare module 'serialport/lib/parsers.js' {
  declare module.exports: $Exports<'serialport/lib/parsers'>;
}
declare module 'serialport/lib/serialport.js' {
  declare module.exports: $Exports<'serialport/lib/serialport'>;
}
